# Generated by Django 5.0.2 on 2024-04-09 09:27

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_alter_crypto_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='crypto',
            managers=[
                ('actual_crypto', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='crypto',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
