# Generated by Django 5.0.2 on 2024-05-26 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_crypto_currency'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='crypto',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='crypto',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('RUB', 'Russian Ruble')], max_length=3),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='time_lastupdate',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('date', models.DateTimeField()),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='crypto.crypto')),
            ],
        ),
    ]
