# Generated by Django 5.0.2 on 2024-06-01 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_alter_crypto_managers_alter_crypto_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_volume', models.DecimalField(decimal_places=5, max_digits=20)),
                ('ethereum_volume', models.DecimalField(decimal_places=5, max_digits=20)),
                ('ripple_volume', models.DecimalField(decimal_places=5, max_digits=20)),
                ('market', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='crypto.market')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='crypto.market')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('posts', models.ManyToManyField(related_name='tags', to='crypto.post')),
            ],
        ),
    ]
