# Generated by Django 5.0.2 on 2024-10-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_remove_marketstats_market_remove_transaction_crypto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='crypto',
            options={'verbose_name': 'Криптовалюта', 'verbose_name_plural': 'Криптовалюты'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
